#!/bin/zsh

if ! command -v kitty >/dev/null 2>&1; then
  osascript <<EOF
  display alert "Error" \
    message "The 'kitty' terminal emulator was not found. Please install Kitty and try again." \
    as critical
EOF
  exit 1
fi

cd "$HOME"

exec arch -arm64 kitty -T 'Neovim' \
  -o map="cmd+n launch --type os-window nvim" \
  -o macos_quit_when_last_window_closed="yes" \
  nvim
